[tool.poetry]
name = "data-analysis"
version = "0.1.0"
description = "data-analysis with Flask"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
